# Generated by Django 3.0.14 on 2021-10-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок вакансии')),
                ('company', models.CharField(max_length=250, verbose_name='Работодатель')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата/Время создания записи')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='Город')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Specialization', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
